CREATE TABLE WALLETS (
    WalletID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    Balance BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_UserWallet FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    CONSTRAINT CHK_BalancePositive CHECK (Balance >= 0)
);

CREATE TABLE TRANSACTIONS (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    WalletID INT NOT NULL,
    TransactionType VARCHAR(20) NOT NULL,
    Amount BIGINT NOT NULL,
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT FK_WalletTransaction FOREIGN KEY (WalletID) REFERENCES WALLETS(WalletID),
    CONSTRAINT CHK_TransactionType CHECK (TransactionType IN ('DEPOSIT', 'WITHDRAW', 'PAYMENT')),
    CONSTRAINT CHK_AmountValue CHECK (Amount > 0),
    CONSTRAINT CHK_Status CHECK (Status IN ('SUCCESS', 'FAILED', 'PENDING'))
);