CREATE TABLE BOOK (
    MaSach CHAR(5) PRIMARY KEY,
    TenSach VARCHAR(200) NOT NULL,
    SoLuong INT CHECK (SoLuong >= 0),
    GiaThue DECIMAL(10, 2) DEFAULT 5000
);

ALTER TABLE BOOK ADD NgayNhap DATE;

CREATE TABLE BORROW_BOOKS (
    MaMuon INT PRIMARY KEY AUTO_INCREMENT,
    MaSach CHAR(5),
    NgayMuon DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BookBorrow FOREIGN KEY (MaSach) REFERENCES BOOK(MaSach)
);